#!/usr/bin/env bash

if [[ ! -f /proc/sys/fs/binfmt_misc/WSLInterop ]]; then
	echo "Your distro do not support WSL Interopability. Installation Aborted."
	exit 1
fi

distro="$(cat /etc/os-release | head -n1 | sed -e 's/NAME="//g')"
if [[ "$distro" == Ubuntu* ]]; then
	distro="ubuntu"
elif [[ "$distro" == openSUSE* ]]; then
	distro="opensuse"
elif [[ "$distro" == SLES* ]]; then
	distro="sles"
fi

function wsl_interop {
	echo -e "WSL Interopability\n*********************"
	cat /proc/sys/fs/binfmt_misc/WSLInterop
	echo ""
}
function wslu_test {
	tests/bats-core/libexec/bats tests/wslpath.bats
}
function wsl_cmd {
	echo -e "\n\ntesting cmd.exe..."
	cmd.exe /c ver
	if [[ $? -eq 0 ]]; then
		echo "cmd.exe can be invoked."
	else
		echo "cmd.exe failed to launch."
		exit 1
	fi
}

function wsl_powershell {
	echo -e "\ntesting powershell.exe..."
	powershell.exe Get-Host
	if [[ $? -eq 0 ]]; then
		echo "powershell.exe can be invoked."
	else
		echo "powershell.exe failed to launch."
		exit 1
	fi
	ppep="`powershell.exe Get-ExecutionPolicy 2>&1 | tail -n1 | sed 's/\r$//'`"
	echo -e "Powershell Execution Policy: $ppep"
	if [[ "$ppep" = "Restricted" ]]; then
		cat << EOF
***************************************
               WARNING
***************************************
The execution policy for powershell.exe
is set to Restricted. You should set P-
owershell Execution Policy to Unrestri-
cted with a Powershell Prompt with Adm-
inistrator right:

   Set-ExecutionPolicy Unrestricted

Due to the limitation, it is not possi-
ble to invoke this command from Bash P-
rompt.
EOF
	fi
}
case $1 in
	--test)
	wslu_test
	;;
	--interop-check)
	wsl_interop
	wsl_cmd
	wsl_powershell
	;;
	-U|--uninstall)
	for f in /usr/share/man/man1/wsl*; do
    	sudo rm -f $f;
		echo "rm -f $f"; 
	done
	for f in /usr/bin/wsl*; do
    	sudo rm -f $f;
		echo "rm -f $f";
	done
	;;
	-r|--reinstall)
	for f in /usr/share/man/man1/wsl*; do
    	sudo rm -f $f;
		echo "rm -f $f"; 
	done
	for f in /usr/bin/wsl*; do
    	sudo rm -f $f;
		echo "rm -f $f";
	done
	for f in src/docs/*.1; do
    	sudo install -m644 $f /usr/share/man/man1;
		echo "Manpage $f copied to /usr/share/man/man1";
	done
	for f in src/wsl*; do
    	sudo install $f /usr/bin;
		echo "exec $f copied to /usr/bin";
	done
	;;
	*)
	echo -e "wslu configuration begins."
	wsl_interop
	wsl_cmd
	wsl_powershell
	echo -e "\nInstall dependencies..."
	case "$distro" in
		'ubuntu')
			sudo apt install build-essential bc ppa-purge wget unzip -y
			;;
		'opensuse')
			sudo zypper -n install bc lsb-release hostname wget unzip
			;;
		'sles')
			sudo zypper -n install bc lsb-release wget unzip
			;;
	esac
	echo -e "\nPre-checking compelete. Installing..."
	for f in src/docs/*.1; do
    	sudo install -m644 $f /usr/share/man/man1;
		echo "Manpage $f copied to /usr/share/man/man1";
	done
	for f in src/wsl*; do
    	sudo install $f /usr/bin;
		echo "exec $f copied to /usr/bin";
	done
	;;
esac
 
