.TH WSLU "1" "May 2017" "0.15.0" "wslu User Manual"

.SH NAME
wslu \- Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslu \fR<commands> [options]

.SH DESCRIPTION
This is a series of utilities for Windows 10 Linux Subsystem, including easier to enable sound and GUI inside the system. 

.SH COMMANDS
.TP
.B help
print a simplified help.
.TP
.B version
print current version.
.TP
.B package
package is a minimal package manager for installing special packages such as WSL pulseaudio and VcXsrv. Also, it provide some simple commands.
.TP
.B fetch
the minimal screen fetch program for Windows 10 Linux Subsystem.
.TP
.B system
the system information for Windows 10 Linux Subsystem.


.SH "SEE ALSO"
https://github.com/patrick330602/wslu
http://garage.patrickwu.cf/man/wslu

.SH AUTHOR
Created and by Patrick Wu J M <wotingwu@live.com>

.SH REPORTING BUGS
Report bugs to <https://github.com/patrick330602/wslu/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
