#!/usr/bin/env bash

# wslu - Windows 10 linux Subsystem Utility Core
# <https://github.com/patrick330602/wslu>

# Copyright(c) 2017 Patrick Wu J M <wotingwu@live.com>

# For more help for wslu, visit the following site:
# http://garage.patrickwu.cf/man/wslu

# data segment
wslu_version=0.21

## color
red=`tput setaf 1`
brown=`tput setaf 3`
blue=`tput setaf 4`
purple=`tput setaf 5`
cyan=`tput setaf 6`
yellow=`tput setaf 7`
orange=`tput setaf 166`
bold=`tput bold`
reset=`tput sgr0`

## indicator
info="${green}[info]${reset}"
error="${red}[error]${reset}"
warn="${orange}[warn]${reset}"
debug="${cyan}[debug]${reset}"

## constants
help_short="wslu (-h|-v|-s)"

function help()
{
	echo -e "`basename "$1"` - Component of Windows 10 Linux Subsystem Utility
Usage: $2

For more help for `basename "$1"`, visit the following site:
http://garage.patrickwu.cf/man/wslu/`basename "$1"`"
}

# commands
## general
case $1 in
	-v|--version) echo "wslu v$wslu_version";;
	-h|--help) help $0 "$help_short";;
	-s|--silent);;
	*)echo "$help_short"; exit 20;;
esac
