.TH WSLU "1" "May 2017" "0.15.0" "wslu User Manual"

.SH NAME
wslu \- Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslu \fR<commands> [options]

.SH DESCRIPTION
Windows 10 Linux Subsystem Utility

.SH COMMANDS
.TP
.B help
print a simplified help.
.TP
.B version
print current version.
.TP
.B package
the minimal package manager for Windows 10 Linux Subsystem.
.TP
.B fetch
the minimal screen fetch program for Windows 10 Linux Subsystem.
.TP
.B system
the system information for Windows 10 Linux Subsystem.


.SH "SEE ALSO"
http://github.com/patrick330602/wslu
http://garage.patrickwu.cf/man/wslu

.SH AUTHOR
Created by Patrick Wu J M <wotingwu@live.com>
.PP
This manual page was written by Patrick Wu J M <wotingwu@live.com>

.SH REPORTING BUGS
Report bugs to <https://github.com/KittyKatt/screenFetch/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
