.TH WSLU "1" "May 2017" "0.15.0" "User Commands"

.SH NAME
wslu \- Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslu \fR<commands> [options]

.SH DESCRIPTION
This is a series of utilities for Windows 10 Linux Subsystem, including easier to enable sound, creating your favorite linux GUI application shortcuts on Windows 10 Desktop. 

.SH COMMANDS
.TP
.B help\fR, \fBh\fR
print a simplified help.
.TP
.B version, \fBv\fR
print current version.
.TP
.B package
package is a minimal package manager for installing special packages such as WSL pulseaudio and VcXsrv. Also, it provide some simple commands to install apps from thirdparty repos.
.RS
.TP
.B count \fR [-n]

.TP
.B fetch
the minimal screen fetch program inspired by \fBufetch\fR and \fBScreenFetch\fR. 
.TP
.B system
system will help print out the system information without any parameters. more options are following:
.RS
.TP
\fB\-B\fR, \fB\-\-build\fR
print Windows build information, for example: \fBWindows 10 Build 16193\fR
.TP
\fB\-K\fR, \fB\-\-kernel\fR
print WSL kernel info, for example: \fBLinux 4.4.0\-43\-Microsoft\fR
.TP
\fB\-R\fR, \fB\-\-release\fR
print WSL system release info, for example: \fBUbuntu 16.04.2 LTS\fR
.RE
.TP
.B shortcut [appname]
shortcut command help you create a shortcut on the Windows 10 Desktop. 

.SH ERROR CODE
.TP
.B 20
input is empty or invalid.
.TP
.B 21
input is empty.
.TP
.B 22
input is invalid.
.TP
.B 30
feature not implemented.

.SH "SEE ALSO"
https://github.com/patrick330602/wslu
http://garage.patrickwu.cf/man/wslu

.SH AUTHOR
Created and by Patrick Wu J M <wotingwu@live.com>

.SH REPORTING BUGS
Report bugs to <https://github.com/patrick330602/wslu/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
