#!/usr/bin/env bash

# wslu - Windows 10 linux Subsystem Utility
# <https://github.com/patrick330602/wslu>

# Copyright(c) 2017 Patrick Wu J M <wotingwu@live.com>

# For more help for wslu, visit the following site:
# http://garage.patrickwu.cf/man/wslu

# data segment
wslu_version=0.16

## color
red=`tput setaf 1`
green=`tput setaf 2`
brown=`tput setaf 3`
blue=`tput setaf 4`
purple=`tput setaf 5`
cyan=`tput setaf 6`
yellow=`tput setaf 7`
bold=`tput bold`
reset=`tput sgr0`

## indicator
info="[${cyan}info${reset}] "
error="[${red}error${reset}] "
warn="[${red}warn${reset}] "

## constants
help_short="wslu [help|version|shortcut|package|system|fetch] <options>"
help="Windows 10 Linux Subsystem Utility
Usage: $help_short

For more help for wslu, visit the following site:
http://garage.patrickwu.cf/wslu"

## Windows side data
path_win()
{
	new_path="$(echo $1 | sed -e 's|\\|\\\\|g')"
	echo $new_path
}
path_linux()
{
	new_path="$(echo $1 | sed -e 's|\\|/|g' -e 's|^\([A-Za-z]\)\:/\(.*\)|/mnt/\L\1\E/\2|')"
	echo $new_path
}
desktop_path=`reg.exe query "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders" /v "Desktop" 2>&1 | sed -n 3p | awk '{ print $3 }' | sed -e 's|\s||g'`
tmp_path=`cmd.exe /k "echo %TMP% && exit" 2>&1`
appdata_path=`cmd.exe /k "echo %USERPROFILE% && exit" 2>&1`
windows_build=`reg.exe query "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v "CurrentBuild" 2>&1 | egrep -o '([0-9]{5})'`

## system info
hostname="$(hostname)"
release="$(lsb_release -d -s)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$((packages+=$(dpkg --get-selections | grep -cv deinstall$)))"
build="Windows 10 Build $windows_build"
shell="$(basename ${SHELL})"


# commands
## general
if [[ "$1" == "version" ]]; then
	if [[ "$2" == "-n" ]]; then
		echo $wslu_version
	else
		echo "wslu v$wslu_version"
	fi
elif [[ "$1" == "help" ]]; then
	echo -e "$help"
## package segment
elif [[ "$1" == "package" ]]; then
	if  [[ "$2" == "count" ]]; then
		echo "Total Installed Package: $packages"
	elif [[ "$2" == "install" ]]; then
		if [[ -n $3 ]]; then
			echo "${info}Adding repository..."
			sudo add-apt-repository -y $3
			echo "${info}Updating source..."
			sudo apt-get update
			echo "${info}Installation begin...."
			sudo apt-get install -y $2
			echo "${info}$2 installed."
		fi
	else
		echo -e "$help"
	fi
## shortcut
elif [[ "$1" == "shortcut" ]]; then
	if [[ -n $2 ]]; then
		cname="$2"
		tpath="$(path_win $tmp_path)"
		dpath="$(path_linux $desktop_path)"
		powershell.exe "\$s=(New-Object -COM WScript.Shell).CreateShortcut('$tpath\\$cname.lnk');\$s.TargetPath='C:\\Windows\\System32\\bash.exe';\$s.Arguments='-c \`\"DISPLAY=:0 $cname\`\"';\$s.Save();"
		tpath="$(path_linux $tmp_path)"
		mv $tpath/$cname.lnk $dpath
		echo "${info}Create shortcut ${cname}.lnk successful"
	else
		echo "${error}No input, aborting"
		exit 20
	fi
## system segment
elif [[ "$1" == "system" ]]; then
	if  [[ "$2" == "-O" ]] || [[ "$2" == "--os-version" ]]; then
		echo $build
	else
		echo "os: $windows_build"
	fi
## fetch segment
elif [[ "$1" == "fetch" ]]; then
	cat <<EOF

${cyan} /\$\$      /\$\$  /\$\$\$\$\$\$  /\$\$       ${red}Windows 10 Linux Subsytem${reset}
${cyan}| \$\$  /\$ | \$\$ /\$\$__  \$\$| \$\$	  ${red}${USER}${reset}@${red}${hostname}${reset}
${cyan}| \$\$ /\$\$\$| \$\$| \$\$${reset}  ${cyan}\\__/| \$\$${reset}       ${red}BUILD:${reset}	${build}
${cyan}| \$\$${reset}${cyan}/\$\$${reset} ${cyan}\$\$${reset} ${cyan}\$\$${reset}${cyan}|  \$\$\$\$\$\$${reset} ${cyan}| \$\$${reset}       ${red}RELEASE:${reset}	${release}
${cyan}| \$\$\$\$${reset}${cyan}_  \$\$\$\$${reset} ${cyan}\\____  \$\$${reset}${cyan}| \$\$${reset}	  ${red}KERNEL:${reset}	${kernel}
${cyan}| \$\$\$${reset}${cyan}/ \\  \$\$\$${reset} ${cyan}/\$\$${reset}  ${cyan}\\ \$\$${reset}${cyan}| \$\$${reset}	  ${red}UPTIME:${reset}	${uptime}
${cyan}| \$\$${reset}${cyan}/   \\  \$\$${reset}${cyan}|  \$\$\$\$\$\$${reset}${cyan}/| \$\$\$\$\$\$\$\$${reset} ${red}SHELL:${reset}	${shell}
${cyan}|__/     \\__/ \\______/ |________/${reset} ${red}PACKAGES:${reset}	${packages}

EOF
else
	echo "$help_short"
fi

