#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/wslview 30
    update-alternatives --install /usr/bin/www-browser www-browser /usr/bin/wslview 30
fi
