#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" = "remove" ] ; then
    update-alternatives --remove x-www-browser /usr/bin/wslview
    update-alternatives --remove www-browser /usr/bin/wslview
    if [ -f /usr/share/wslu/updated_time ]; then
        rm /usr/share/wslu/updated_time
    fi
    if [ -f /usr/share/applications/wslview.desktop ]; then
        rm /usr/share/applications/wslview.desktop
        update-desktop-database
    fi
fi

