.TH "WSLACT" "1" "DATEPLACEHOLDER" "VERSIONPLACEHOLDER" "WSL Utilities User Manual"
.SH NAME
.B wslact
- Component of Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslact
.RB COMMAND
.I ...
.SH DESCRIPTION
A set of quick actions for WSL such as creating startup tasks and manually sync time between Windows ans WSL.
.PP
Currently, we have two features available:
.in +4n
.nf
\fBts, time-sync\fR \- Time Sync
\fBsm, smart-mounting\fR \- Smart Mounting
.fi
.in
.SH COMMANDS
.SS "Time Sync"
Time Sync (
.B time-sync
) feature allows user to manually sync time from Windows to WSL. Sometime, when you have network issues, WSL time will be slower than the Windows time. This tool is designed for this situation.
.SH OPTIONS
.TP
.B -h, --help
print a simple help.
.TP
.B -v, --version
print current version.
.SH AUTHOR
Created by Patrick Wu <me@patrickwu.space>
.SH REPORTING BUGS
Report bugs to <https://github.com/wslutilities/wslu/issues>
.SH COPYRIGHT
This is free software; you can redistribute it and/or modify it under
the terms of the GNU GPL version 3 or (at your option) any later
version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
.SH SEE ALSO
wslu(7)