.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WSLFETCH" "1" "January 2019" "Patrick Wu" "WSLFETCH"
.


.
.SH "NAME"
wslfetch \- Component of Windows 10 Linux Subsystem Utility
.
.SH "Synopsis"
\fBwslfetch (\-h|\-v|\-s|\-l)\fR
.
.SH "Description"
This is a WSL Screenshot Information Tool to print information in a elegant way\.
.
.SH "COMMANDS"
\fB\-h, \-\-help\fR \- print a simple help
.
.P
\fB\-v, \-\-version\fR \- print current version
.
.P
\fB\-l, \-\-line\fR \- print a separate line before and after
.
.P
\fB\-s, \-\-splash\fR \- use wslfetch as splash when startup; add \'wslfetch \-\-splash\' to the end of the rc file
