.TH WSLFETCH "1" "May 2017" "0.20.17" "User Commands"

.SH NAME
wslfetch \- Component of Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslfetch\fR (\-h|\-v|\-s|\-l)

.SH DESCRIPTION
This is a WSL Screenshoot Information Tool to print information in a elegant way.

.SH COMMANDS
.TP
.B \-h\fR, \fB\-\-help\fR
print a simple help
.TP
.B \-v\fR, \fB\-\-version\fR
print current version
.TP
.B \-l\fR, \fB\-\-line\fR
print a seperate line before and after
.TP
.B \-s\fR, \fB\-\-splash\fR
use wslfetch as spash when startup; add wslfetch --splash to the end of the rc file 

.SH "SEE ALSO"
https://github.com/patrick330602/wslu

.SH AUTHOR
Created by Patrick Wu J M <wotingwu@live.com>; inspired by ufetch and screenfetch

.SH REPORTING BUGS
Report bugs to <https://github.com/patrick330602/wslu/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.