.TH WSLPATH "1" "May 2017" "1.1" "User Commands"

.SH NAME
wslpath \- Component of Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslpath\fR (\-w|\-d|\-u|\-m|\-r) [\-D|\-A|\-T|\-S|\-W|\-s|\-su|\-H|\-P|...NAME...]
.B wslpath\fR (\-h|\-v|\-R)

.SH DESCRIPTION
This is a WSL Windows path Converter that can convert Windows path to other styles of path.

.SH COMMANDS
Output Type Options:
.RS
.TP
.B \-w\fR, \fB\-\-windows\fR
print Windows form of path(C:\Windows\System32)
.TP
.B \-d\fR, \fB\-\-windows\-double\-slash\fR
print Windows form of path with double backslash(C:\\Windows\\System32)
.TP
.B \-u\fR, \fB\-\-unix\fR
print Unix form of path(/mnt/c/Windows/System32)
.TP
.B \-m\fR, \fB\-\-mixed\fR
print Windows form of path(C:\Windows\System32)
.TP
.B \-r\fR, \fB\-\-reg-data\fR
use the registry data to print path[wslpath \-R to know more]
.RE
System Path:
.RS
.TP
.B \-D\fR, \fB\-\-desktop\fR
print desktop path and exit
.TP
.B \-A\fR, \fB\-\-appdata\fR
print AppData path(%APPDATA%) and exit
.TP
.B \-T\fR, \fB\-\-temp\fR
print temp path(%TMP%) and exit
.TP
.B \-S\fR, \fB\-\-sysdir\fR
print system path and exit
.TP
.B \-W\fR, \fB\-\-windir\fR
print Windows path and exit
.TP
.B \-s\fR, \fB\-\-start\-menu\fR
print Start Menu path and exit
.TP
.B \-su\fR, \fB\-\-startup\fR
print Startup path and exit
.TP
.B \-H\fR, \fB\-\-home\fR
print user home path(%HOMEPATH%) and exit
.TP
.B \-P\fR, \fB\-\-program-files\fR
print Program Files path(%ProgramFiles%) and exit
.RE
Other Options:
.RS
.TP
.B \-h\fR, \fB\-\-help\fR
print a simple help
.TP
.B \-v\fR, \fB\-\-version\fR
print current version
.TP
.B \-R\fR, \fB\-\-avail\-reg\fR
print available registery input
.RS 

.SH "SEE ALSO"
https://github.com/patrick330602/wslu

.SH AUTHOR
Created by patrickwu <wotingwu@live.com>

.SH REPORTING BUGS
Report bugs to <https://github.com/patrick330602/wslu/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
