.TH WSLSYS "1" "May 2017" "1.0.06" "User Commands"

.SH NAME
wslsys \- Component of Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslsys\fR (\-h|\-v|\-S|\-U|\-B|\-R|\-K|\-P)

.SH DESCRIPTION
This is a WSL system information printer to print out some basic system information.

.SH COMMANDS
Default will print out the overall system information. more options are following:
.TP
.B \-h\fR, \fB\-\-help\fR
print a simple help
.TP
.B \-v\fR, \fB\-\-version\fR
print current version
.TP
\fB\-S\fR, \fB\-\-shell\fR
print used shell
.TP
\fB\-U\fR, \fB\-\-uptime\fR
print current uptime
.TP
\fB\-B\fR, \fB\-\-build\fR
print Windows build information
.TP
\fB\-K\fR, \fB\-\-kernel\fR
print WSL kernel info
.TP
\fB\-R\fR, \fB\-\-release\fR
print WSL system release info
.TP
\fB\-P\fR, \fB\-\-package\fR
print total installed packages

.SH "SEE ALSO"
https://github.com/patrick330602/wslu

.SH AUTHOR
Created by Patrick Wu J M <wotingwu@live.com>

.SH REPORTING BUGS
Report bugs to <https://github.com/patrick330602/wslu/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.