.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WSLSYS" "1" "January 2019" "Patrick Wu" "WSLSYS"
.

\fBwslsys\fR
.
.SH "NAME"
wslsys \- Component of Windows 10 Linux Subsystem Utility
.
.SH "Synopsis"
\fBwslsys (\-h|\-v|\-S|\-U|\-b|\-B|\-fB|\-R|\-K|\-P) \-s\fR
.
.SH "Description"
This is a WSL system information printer to print out some basic system information\.
.
.SH "Commands"
Default will print out the overall system information\. more options are following(add \-s flag to print only value):
.
.P
\fB\-h, \-\-help\fR \- print a simple help
.
.P
\fB\-v, \-\-version\fR \- print current version
.
.P
\fB\-S, \-\-shell\fR \- print used shell
.
.P
\fB\-U, \-\-uptime\fR \- print current uptime
.
.P
\fB\-b, \-\-branch\fR \- print windows build information
.
.P
\fB\-B, \-\-build\fR \- print Windows build information
.
.P
\fB\-fB, \-\-full\-build\fR \- print full Windows build information
.
.P
\fB\-K, \-\-kernel\fR \- print WSL kernel info
.
.P
\fB\-R, \-\-release\fR \- print WSL system release info
.
.P
\fB\-P, \-\-package\fR \- print total installed packages
