.TH WSLUSC "1" "May 2017" "1.0.03" "User Commands"

.SH NAME
wslusc \- Component of Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslusc\fR (\-g|\-h|\-v) ..NAME...

.SH DESCRIPTION
This is a WSL shortcut creator to create shortcut on Windows Desktop

.SH COMMANDS
.TP
.B \-h\fR, \fB\-\-help\fR
print a simple help
.TP
.B \-v\fR, \fB\-\-version\fR
print current version
.TP
.B \-g\fR, \fB\-\-gui\fR
create a shortcut that links to a GUI application

.SH "SEE ALSO"
https://github.com/patrick330602/wslu

.SH AUTHOR
Created by Patrick Wu J M <wotingwu@live.com>

.SH REPORTING BUGS
Report bugs to <https://github.com/patrick330602/wslu/issues>

.SH COPYRIGHT
This is free software; you can redistribute it and/or modify
it under the terms of the GNU GPL version 3 or (at your option) any later version.
There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.