.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WSLUSC" "1" "January 2019" "Patrick Wu" "WSLUSC"
.

\fBwslusc\fR
.
.SH "NAME"
wslusc \- Component of Windows 10 Linux Subsystem Utility
.
.SH "Synopsis"
\fBwslusc (\-g|\-h|\-v) \.\.NAME\.\.\.\fR
.
.SH "Description"
This is a WSL shortcut creator to create shortcut on Windows Desktop
.
.SH "Commands"
\fB\-h, \-\-help\fR \- print a simple help
.
.P
\fB\-v, \-\-version\fR \- print current version
.
.P
\fB\-g, \-\-gui\fR \- create a shortcut that links to a GUI application
