.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WSLVIEW" "1" "January 2019" "Patrick Wu" "WSLVIEW"
.

\fBwslview\fR
.
.SH "NAME"
wslview \- Component of Windows 10 Linux Subsystem Utility
.
.SH "SYNOPSIS"
\fBwslview (\-u|\-r|\-h|\-v) \.\.\.LINK\.\.\.\fR
.
.SH "DESCRIPTION"
This is a fake WSL browser that can help you open link in default Windows browser\.
.
.SH "COMMANDS"
\fB\-h, \-\-help\fR \- print a simple help
.
.P
\fB\-v, \-\-version\fR \- print current version
.
.P
\fB\-u, \-\-unregister\fR \- remove \fBwslview\fR as the default WSL web browser\.
.
.P
\fB\-r, \-\-register\fR \- register \fBwslview\fR as the default WSL web browser\.
.
.SH "SEE ALSO"
https://github\.com/wslutilities/wslu
.
.SH "AUTHOR"
Created by Patrick Wu \fIwotingwu@live\.com\fR
.
.SH "REPORTING BUGS"
Report bugs to \fIhttps://github\.com/wslutilities/wslu/issues\fR
.
.SH "COPYRIGHT"
This is free software; you can redistribute it and/or modify it under the terms of the GNU GPL version 3 or (at your option) any later version\. There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\.
