.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WSLVAR" "1" "January 2019" "Patrick Wu" "WSLVAR"
.

\fBwslvar\fR
.
.SH "NAME"
wslvar \- Component of Windows 10 Linux Subsystem Utility
.
.SH "SYNOPSIS"
.
.nf

wslvar (\-s|\-l) \.\.\.NAME\.\.\.
wslvar (\-h|\-v|\-S|\-L)
.
.fi
.
.SH "DESCRIPTION"
This is a WSL tool to help you get Windows system environment variables\.
.
.SH "COMMANDS"
.
.SS "Output Type Options"
\fB\-s, \-\-sys\fR \- use data from system local & global variables\.
.
.P
\fB\-l, \-\-shell\fR \- use data from Shell folder environment variables\.
.
.SS "Other Options"
\fB\-h, \-\-help\fR \- print a simple help\.
.
.P
\fB\-v, \-\-version\fR \- print current version\.
.
.P
\fB\-S, \-\-getsys\fR \- show available system local & global variables\.
.
.P
\fB\-L, \-\-getshell\fR \- show available Shell folder environment variables\.
.
.SH "SEE ALSO"
https://github\.com/wslutilities/wslu
.
.SH "AUTHOR"
Created by Patrick Wu \fIwotingwu@live\.com\fR
.
.SH "REPORTING BUGS"
Report bugs to \fIhttps://github\.com/wslutilities/wslu/issues\fR
.
.SH "COPYRIGHT"
This is free software; you can redistribute it and/or modify it under the terms of the GNU GPL version 3 or (at your option) any later version\. There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\.
