.TH "WSLVIEW" "1" "DATEPLACEHOLDER" "VERSIONPLACEHOLDER" "WSL Utilities"

.SH NAME
.B wslview
Component of Windows 10 Linux Subsystem Utility
.SH SYNOPSIS
.B wslview
(--register|--unregister|--help|--version) [LINK]
.SH DESCRIPTION
This is a fake WSL browser that can help you open link in default Windows browser\.
.SH COMMANDS
.B -h, --help
print a simple help
.PP
.B -v, --version
print current version
.PP
.B -u, --unregister
remove \fBwslview\fR as the default WSL web browser\.
.PP
.B -r, --register
register \fBwslview\fR as the default WSL web browser\.
.SH SEE ALSO
https://wslu.patrickwu.space
.SH AUTHOR
Created by Patrick Wu <me@patrickwu.space>
.SH REPORTING BUGS
Report bugs to <https://github.com/wslutilities/wslu/issues>
.SH COPYRIGHT
This is free software; you can redistribute it and/or modify it under the terms of the GNU GPL version 3 or (at your option) any later version. There is NO warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.