.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WSLVAR" "1" "January 2019" "Patrick Wu" "WSLVAR"
.

\fBwslvar\fR
.
.SH "NAME"
wslvar \- Component of Windows 10 Linux Subsystem Utility
.
.SH "Synopsis"
\fBwslvar (\-s|\-l) \.\.\.NAME\.\.\.\fR
.
.P
\fBwslvar (\-h|\-v|\-S|\-L)\fR
.
.SH "Description"
This is a WSL tool to help you get Windows system environment variables\.
.
.SH "Commands"
.
.SS "Output Type Options"
\fB\-s, \-\-sys\fR \- use data from system local & global variables\.
.
.P
\fB\-l, \-\-shell\fR \- use data from Shell folder environment variables\.
.
.SS "Other Options"
\fB\-h, \-\-help\fR \- print a simple help\.
.
.P
\fB\-v, \-\-version\fR \- print current version\.
.
.P
\fB\-S, \-\-getsys\fR \- show available system local & global variables\.
.
.P
\fB\-L, \-\-getshell\fR \- show available Shell folder environment variables\.
