#!/usr/bin/env bash
# wsluconf - WSLU configuration system
# Component of Windows 10 linux Subsystem Utility
# <https://github.com/patrick330602/wslu>

# Copyright(c) 2018 Patrick Wu J M <wotingwu@live.com>

version="01"

. wslu --silent