#!/usr/bin/env bash
# wslterm - WSL terminal launcher(Beta)
# Component of Windows 10 linux Subsystem Utility
# <https://github.com/patrick330602/wslu>

# Copyright(c) 2018 Patrick Wu J M <wotingwu@live.com>

# For more help for wslterm, visit the following site:
# http://garage.patrickwu.cf/man/wslu/wslterm

version="00"

. wslu --silent

help_short="wslterm (-h|-v) ..NAME..."

for args; do
	case $args in
		-h|--help) help $0 "$help_short"; exit;;
		-v|--version) echo "wslterm v$wslu_version.$version"; exit;;
		*) ;;
	esac
done

powershell.exe "Start-Process -FilePath 'C:\\Users\\wotin\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Ubuntu Terminal.lnk'"
